/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubmissionFilter = IDL.Variant({
  'region' : IDL.Text,
  'contributorName' : IDL.Text,
  'status' : IDL.Text,
  'language' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'emailOrPhone' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ContributionSubmission = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'region' : IDL.Text,
  'contributorName' : IDL.Text,
  'status' : IDL.Text,
  'recordingType' : IDL.Text,
  'submittedAt' : Time,
  'language' : IDL.Text,
  'transcription' : IDL.Text,
  'category' : IDL.Text,
});
export const KnowledgeEntry = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'title' : IDL.Text,
  'verified' : IDL.Bool,
  'description' : IDL.Text,
  'audioUrl' : IDL.Text,
  'language' : IDL.Text,
  'transcription' : IDL.Text,
  'category' : IDL.Text,
  'contributorAge' : IDL.Nat,
});

export const idlService = IDL.Service({
  'filterContributions' : IDL.Func(
      [SubmissionFilter],
      [IDL.Vec(ContributionSubmission)],
      ['query'],
    ),
  'getAllContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getAllKnowledgeEntries' : IDL.Func([], [IDL.Vec(KnowledgeEntry)], ['query']),
  'getContributionById' : IDL.Func(
      [IDL.Text],
      [ContributionSubmission],
      ['query'],
    ),
  'getKnowledgeEntriesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(KnowledgeEntry)],
      ['query'],
    ),
  'getKnowledgeEntryById' : IDL.Func([IDL.Text], [KnowledgeEntry], ['query']),
  'searchKnowledgeEntriesByKeyword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(KnowledgeEntry)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitContribution' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubmissionFilter = IDL.Variant({
    'region' : IDL.Text,
    'contributorName' : IDL.Text,
    'status' : IDL.Text,
    'language' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'emailOrPhone' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ContributionSubmission = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'region' : IDL.Text,
    'contributorName' : IDL.Text,
    'status' : IDL.Text,
    'recordingType' : IDL.Text,
    'submittedAt' : Time,
    'language' : IDL.Text,
    'transcription' : IDL.Text,
    'category' : IDL.Text,
  });
  const KnowledgeEntry = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'title' : IDL.Text,
    'verified' : IDL.Bool,
    'description' : IDL.Text,
    'audioUrl' : IDL.Text,
    'language' : IDL.Text,
    'transcription' : IDL.Text,
    'category' : IDL.Text,
    'contributorAge' : IDL.Nat,
  });
  
  return IDL.Service({
    'filterContributions' : IDL.Func(
        [SubmissionFilter],
        [IDL.Vec(ContributionSubmission)],
        ['query'],
      ),
    'getAllContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getAllKnowledgeEntries' : IDL.Func(
        [],
        [IDL.Vec(KnowledgeEntry)],
        ['query'],
      ),
    'getContributionById' : IDL.Func(
        [IDL.Text],
        [ContributionSubmission],
        ['query'],
      ),
    'getKnowledgeEntriesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(KnowledgeEntry)],
        ['query'],
      ),
    'getKnowledgeEntryById' : IDL.Func([IDL.Text], [KnowledgeEntry], ['query']),
    'searchKnowledgeEntriesByKeyword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(KnowledgeEntry)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitContribution' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
