/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface KnowledgeEntry {
    id: string;
    region: string;
    title: string;
    verified: boolean;
    description: string;
    audioUrl: string;
    language: string;
    transcription: string;
    category: string;
    contributorAge: bigint;
}
export type Time = bigint;
export interface ContactSubmission {
    name: string;
    emailOrPhone: string;
    message: string;
    timestamp: Time;
}
export interface ContributionSubmission {
    id: string;
    age: bigint;
    region: string;
    contributorName: string;
    status: string;
    recordingType: string;
    submittedAt: Time;
    language: string;
    transcription: string;
    category: string;
}
export type SubmissionFilter = {
    __kind__: "region";
    region: string;
} | {
    __kind__: "contributorName";
    contributorName: string;
} | {
    __kind__: "status";
    status: string;
} | {
    __kind__: "language";
    language: string;
} | {
    __kind__: "category";
    category: string;
};
export interface backendInterface {
    filterContributions(filter: SubmissionFilter): Promise<Array<ContributionSubmission>>;
    getAllContactSubmissions(): Promise<Array<ContactSubmission>>;
    getAllKnowledgeEntries(): Promise<Array<KnowledgeEntry>>;
    getContributionById(id: string): Promise<ContributionSubmission>;
    getKnowledgeEntriesByCategory(category: string): Promise<Array<KnowledgeEntry>>;
    getKnowledgeEntryById(id: string): Promise<KnowledgeEntry>;
    searchKnowledgeEntriesByKeyword(keyword: string): Promise<Array<KnowledgeEntry>>;
    submitContactForm(name: string, emailOrPhone: string, message: string): Promise<void>;
    submitContribution(contributorName: string, age: bigint, region: string, language: string, transcription: string, category: string, recordingType: string): Promise<string>;
}
import type { SubmissionFilter as _SubmissionFilter } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async filterContributions(arg0: SubmissionFilter): Promise<Array<ContributionSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterContributions(to_candid_SubmissionFilter_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterContributions(to_candid_SubmissionFilter_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactSubmissions();
            return result;
        }
    }
    async getAllKnowledgeEntries(): Promise<Array<KnowledgeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKnowledgeEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKnowledgeEntries();
            return result;
        }
    }
    async getContributionById(arg0: string): Promise<ContributionSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.getContributionById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContributionById(arg0);
            return result;
        }
    }
    async getKnowledgeEntriesByCategory(arg0: string): Promise<Array<KnowledgeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKnowledgeEntriesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKnowledgeEntriesByCategory(arg0);
            return result;
        }
    }
    async getKnowledgeEntryById(arg0: string): Promise<KnowledgeEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getKnowledgeEntryById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKnowledgeEntryById(arg0);
            return result;
        }
    }
    async searchKnowledgeEntriesByKeyword(arg0: string): Promise<Array<KnowledgeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchKnowledgeEntriesByKeyword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchKnowledgeEntriesByKeyword(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return result;
        }
    }
    async submitContribution(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContribution(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContribution(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
}
function to_candid_SubmissionFilter_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionFilter): _SubmissionFilter {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "region";
    region: string;
} | {
    __kind__: "contributorName";
    contributorName: string;
} | {
    __kind__: "status";
    status: string;
} | {
    __kind__: "language";
    language: string;
} | {
    __kind__: "category";
    category: string;
}): {
    region: string;
} | {
    contributorName: string;
} | {
    status: string;
} | {
    language: string;
} | {
    category: string;
} {
    return value.__kind__ === "region" ? {
        region: value.region
    } : value.__kind__ === "contributorName" ? {
        contributorName: value.contributorName
    } : value.__kind__ === "status" ? {
        status: value.status
    } : value.__kind__ === "language" ? {
        language: value.language
    } : value.__kind__ === "category" ? {
        category: value.category
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
